### ISSUE TITLE
浏览器报错：Your connection is not private

### ISSUE THREAD

**Issue by CyrusYip** [enixam/qiushi.rbind.io#3]
![image](https://user-images.githubusercontent.com/60951091/120921096-a0618e80-c6f4-11eb-869d-1565f42fbe7e.png)

解决办法：<https://github.com/rbind/support/issues/797#issuecomment-830434719>

**Comment by enixam** [comment]
感谢提醒

**Comment by CyrusYip** [comment]
已经修复了😄
